### ISSUE TITLE
Font Awesome

### ISSUE THREAD

**Issue by emiluzelac** [senlin/soblossom#10]
It is always good idea to include resources within the theme and since you are already doing this for the rest, I would highly recommend to add the following too:

```
	/**
	 * Return the Font Awesome stylesheet URL, when Font Awesome gets updated, just change this URL
	 * @link: fontawesome.io/get-started/
	 */
	function soblossom_fontawesome_url() {
		$fontawesome_url = '//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css';
	
		return $fontawesome_url;
	}
```

This way user will be able to control the stylesheet and also combine when needed to.

**Comment by senlin** [comment]
Not sure I understand. 

Do you mean that instead of using the call to the source on maxcdn, I should add the font to the theme?

**Comment by emiluzelac** [comment]
Yes, add the font in.

**Comment by senlin** [comment]
Hmmm, okay that is less flexible though.
In the current situation if the font receives an update, all that you need to do is to change a digit. 
If I were to physically add the font to the theme, then a lot more work is needed to update the font.
Of course that also depends on how the font is added. If through Grunt, then it would be updated when doing a `bower update`, but not everyone will do that.

I'll think about this one, perhaps I will add some documentation to explain the above, so people can choose which way they prefer to do it...
