### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by emiluzelac** [senlin/soblossom#13]
Add an actual screenshot of your theme, instead of a logo.

**Comment by senlin** [comment]
Let's agree to disagree on this one too :)

It's a starter theme, this way I think I encourage people to change it to whatever they have build with/on top of soblossom.

**Comment by senlin** [comment]
replaced wontfix label with NA label
reason that it is not applicable, is because I ordered the Theme Review service not with the intend to submit soblossom to the WP.org Theme Repo, but to get an outside independent assessment of the quality of the code.
