### ISSUE TITLE
Custom menu placeholders

### ISSUE THREAD

**Issue by emiluzelac** [senlin/soblossom#14]
There are many situations where users don't want to use menus, or at least any extra ones, like footer area. Theme also uses a main menu, but additional menu is being added as well. I would highly recommend to have a main one in and leave the rest empty without any notices.

**Comment by senlin** [comment]
Let's agree to disagree on this one :)

It's a starter theme, so I have included a few things with clear information on what to do. If the user doesn't want the additional stuff, then it is encouraged to remove it.

**Comment by senlin** [comment]
replaced wontfix label with NA label
reason that it is not applicable, is because I ordered the Theme Review service not with the intend to submit soblossom to the WP.org Theme Repo, but to get an outside independent assessment of the quality of the code.
