### ISSUE TITLE
Second home link

### ISSUE THREAD

**Issue by emiluzelac** [senlin/soblossom#16]
Is the second home link added purposely? It seem like it can't be managed via custom menus.
![screen shot 2015-01-08 at 5 26 50 pm](https://cloud.githubusercontent.com/assets/1784526/5672975/e33fb076-975b-11e4-8a34-676fc8352823.png)

**Comment by senlin** [comment]
If you mean the link on the left, yes this is added "on purpose", so you won't need to add a separate link for the home page.
You can change it to anything you'd like via the navigation template parts.

**Comment by emiluzelac** [comment]
Thanks :)
