### ISSUE TITLE
Aqua Resizer

### ISSUE THREAD

**Issue by emiluzelac** [senlin/soblossom#17]
Aqua Resizer is redundant, WordPress is also able to resize on the fly: http://codex.wordpress.org/Function_Reference/add_image_size#Crop_Mode

**Comment by senlin** [comment]
Although that might be true, the native WP function cannot [upscale](https://github.com/syamilmj/Aqua-Resizer/wiki) I believe?

**Comment by emiluzelac** [comment]
As in featured images, the sizes are what we add in the functions, you cannot enlarge with it no. But again, I am thinking under what condition one would need that anyways :)

**Comment by senlin** [comment]
I can show you plenty of samples when it is desirable to be able to upscale an image. Working with clients and bespoke designs is far from an ideal world ;)

**Comment by senlin** [comment]
replaced wontfix label with NA label
reason that it is not applicable, is because I ordered the Theme Review service not with the intend to submit soblossom to the WP.org Theme Repo, but to get an outside independent assessment of the quality of the code.

**Comment by emiluzelac** [comment]
:+1:
