### ISSUE TITLE
Small spacing issue

### ISSUE THREAD

**Issue by emiluzelac** [senlin/soblossom#18]
```This article was posted in Uncategorized and tagged . Bookmark the permalink.Edit```

Make ```tagged``` closer to ```.``` and separate ```permalink.``` from the ```Edit```

**Comment by senlin** [comment]
I don't understand. 
That line should show when there are actually tags. Perhaps I made a mistake in the [condition](https://github.com/senlin/soblossom/blob/master/inc/soblossom.php#L331-335)?

**Comment by emiluzelac** [comment]
Yes, definitely something to do with ```if ( ! function_exists( 'soblossom_posted_in' ) ) {```. Also noticed that it says tagged, but no tags are showing. Just realized that as well.

**Comment by senlin** [comment]
okay, will look further into that then, perhaps I have to turn the conditions around a bit.

**Comment by senlin** [comment]
The strangest is that I have copied this directly from [Underscores](https://github.com/Automattic/underscores.me/blob/master/content-single.php) any clues?

**Comment by senlin** [comment]
Found the culprit.

I added to `<span itemprop="keywords">` to the output of  `$tag_list` and because it then always outputs the opening and closing spans `if ( '' != $tag_list )` is always false.

**Comment by emiluzelac** [comment]
Wonderful, I am glad that you found it :)
