### ISSUE TITLE
Request for code without Grunt

### ISSUE THREAD

**Issue by ariane1001** [senlin/soblossom#21]
Hi,
I am very impressed by your soblossom theme. I would like to use it but without Grunt.
In the Read Me you talk about adjusting the enqueueing of styles and scripts in the inc/soblossom.php file (lines 168-210).
I have no idear what the should be if I wanted to use, for example, Prepros compiler. Do you have an example?

Thanks in advance,
Ariane

**Comment by senlin** [comment]
Great to hear that you like soblossom so much!

And you ask an excellent question. I have therefore just changed the file by adding a [better explanation](https://github.com/senlin/soblossom/blob/master/inc/soblossom.php#L164-L177) at the top of the `soblossom_scripts()` function as well as an [alternative function](https://github.com/senlin/soblossom/blob/master/inc/soblossom.php#L218-L245) that you can use when not using Grunt.

I hope this explains it a bit better and helps you to make it work with a different compiler.

Also don't forget to send me a link of what you made with soblossom, so I can add it to the [flowers page](http://so-wp.com/themes/soblossom/flowers/) on the website :)

**Comment by ariane1001** [comment]
Hi Piet,
Thanks for the alternative function you made for non Grunt users. 
I still can't get it to work though, compiling is still nog working as it should be. 
Prepos can compile with Use LibSass and with Compass. In both cases I get the same error: "File to import not found or unreadable: foundation/functions"
I have searched and read a lot online but cannot get it to work.
Any idear what is the problem?

I don't know if this is the place to ask my question so I if you think this is not the proper place, thanks again for you help so far.
Cheers Ariane

**Comment by senlin** [comment]
Hi Ariane, I have never worked with the Prepos compiler and therefore have no clue. Perhaps you need to adjust some files to make soblossom suitable for that compiler? I would take it up with the Prepos support on how to make things suitable for compiling. Sorry I cannot help you any further with this, hope you solve it.

**Comment by ariane1001** [comment]
Hi Piet,
Thanks for the quick reply, I will contact PrePros support and let you know when I got it working.
Cheers

**Comment by senlin** [comment]
Yes, would be interesting to know, so I could add that to the Readme file :)
