### ISSUE TITLE
Cannot get the translation to work

### ISSUE THREAD

**Issue by zitrusblau** [senlin/soblossom#22]
Hi Piet,

at first congrats to this great work!

I translated the theme into german language but cannot get the language files work. I'll try all possibilities, save the .mo and .po files in the themes /languages folder, named as soblossom-de_DE.po and soblossom-de_DE.mo also named only by the locale (de_DE.mo, de_DE.po), which is actually recommended by WordPress. Nothing work, also if the language files would be stored in wp-content/languages.

I also try to activate the build-in dutch language, this also don't work.

So what is the trick to get the correct language working?

sincerely yours
Tina

**Comment by senlin** [comment]
Hi Tina,
Thanks for your message, glad you like the soblossom theme :)

Strange that you cannot get it to work. To be honest we only use language files with the WPML plugin and it normally picks up the translation if it is there.

To use the language files on a standalone language site, I think you first need to set the site language to German or Dutch (under Settings). Then the WordPress should automatically look for the translation files in the folder we instruct it to look at in the [inc/soblossom.php file](https://github.com/senlin/soblossom/blob/master/inc/soblossom.php#L37): the languages folder.

Naming of your files should indeed be soblossom-de_DE.po and soblossom-de_DE.mo

I can try tomorrow if I can get it working on a test install, I'm a bit busy at the moment. Hope that's okay with you.

Thanks,
Piet

**Comment by zitrusblau** [comment]
Hi Piet,

thanks for you're fast reply, and sorry for this confusion!

I find out now the translation is working. I tested this at first on a template file which I've added and the strings on this template naturally are not included at the POT. So they cannot be translated. (facepalm)

So no need to get in action for you!

thanks,
Tina

**Comment by senlin** [comment]
Hi Tina,

Great stuff, happy to hear it works then after all!

If you want, you can send the German translation as a Pull Request, so I can include that in the theme (accrediting you of course). 

Also, if you build a cool site with soblossom, I would love to include it on the Flowers page: http://so-wp.com/themes/soblossom/flowers/

Thanks,
Piet

**Comment by zitrusblau** [comment]
Hi Piet,

after adding the missing strings I try it again and it don't work. So have to sleep a night about this and now I made a new clean instance of WP without any plugin, activate the soblossom theme and dutch language, it still don't work.
So I try another theme with another language and this work! So I compare the language files of both themes and find out that the theme which work with another language, have another naming for the language files. Like it is mentioned here: https://codex.wordpress.org/Function_Reference/load_theme_textdomain under the point Examples->1st Example the language files must be named only with language code. I renamed the files and all work fine!

After completing the templates and the site I'll send you the german language files and a link for your flowers page.

Sincerely
Tina

**Comment by senlin** [comment]
Hi Tina,
Wow, I really didn't know that. Good to know!
Will you also include the renamed Dutch files in your PR or do you want me to do that?
Please let me know.
Thanks a lot for figuring this out!
Piet

**Comment by zitrusblau** [comment]
Hi Piet,

I've comitted the po-files for dutch and german language and made pull requests. But it's the first time I've uploading files to github. I hope it's all right. And I don't know how to commit the mo-files, is it possible to paste the mo code in the new file window? I cannot find an upload button and I'm not sure about the binary code.

**Comment by senlin** [comment]
Hi Tina, I have just merged the Dutch .po file, but I am not sure what you have done, because the original files are still there. 

Usually what you need to do is to first fork the soblossom theme. Then make your changes, i.e. renaming the `soblossom-nl_NL.po` file to `nl_NL.po` and the same for the .mo file. Then add your German language files and then commit those changes to your fork. Once the file changes are committed **and** pushed up to your repository, then you can send me a Pull Request (PR) and I can accept that.
Does that help?

**Comment by senlin** [comment]
Oh I see the German PR now :)

**Comment by senlin** [comment]
I will do the mo files then, unless of course you want the exercise ;)

**Comment by zitrusblau** [comment]
I'll keep it in mind for future. In this moment i don't have much time for exercising. The GIT technique often is a bit overdosed for me, I'm only a simple templaterin and we work with our own GIT over SourceTree and sometimes I feel like it's another galaxy. ;)

**Comment by senlin** [comment]
Okay, no worries, I will remove the Dutch files then and generate the .mo files. Thanks a lot anyways!
