### ISSUE TITLE
Foundation Bug

### ISSUE THREAD

**Issue by zitrusblau** [senlin/soblossom#25]
Hi Piet,

I've found a foundation bug and want to give you a notice. Maybe you already know this: https://github.com/zurb/foundation-sites/issues/6839

So you're soblossom_featured_image() won't work correctly. I found this bug because I've adapted you're function for a gallery output.

Sincerelys
Tina

**Comment by senlin** [comment]
thanks @zitrusblau for catching this, making the changes now
