### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by emiluzelac** [senlin/soblossom#3]
If you are submitting to WPORG, but also leaving users with an option to use plugin to add Favicon, such as Jetpack, which is widely used, I would recommend to either wrap within some type of option or completely remove:

```
		<!--[if IE]>
			<link rel="shortcut icon" href="<?php echo get_template_directory_uri(); ?>/favicon.ico">
		<![endif]-->
```

Also, Favicons don't need to be in IE statement, all browsers would support them equally (excluding iOS mobile devices) http://en.wikipedia.org/wiki/Favicon#How_to_use Additionally, Favicons are located inside of https://github.com/senlin/soblossom/tree/master/images folder which is missing from the above URL.

This will be more than enough:

```
/**
 * ADD FAVICON TO HEAD
 *
 * @sizes: graphicdesign.stackexchange.com/a/27142
 * @cheatsheet: github.com/audreyr/favicon-cheat-sheet
 */
	add_action( 'wp_head', 'soblossom_add_favicon' );
	function soblossom_add_favicon() {
	    echo '<link rel="apple-touch-icon-precomposed" href="' . get_template_directory_uri() . '/images/favicon-152.png">';
	    echo '<link rel="shortcut icon" href="' . get_template_directory_uri() . '/images/favicon-96.png" />';
	
	}
```

the last one is identical to what you have in header.php with ```-96``` exception.

**Comment by senlin** [comment]
Ah okay, I understand. I though that .ico was still used by IE, but  then it has to be placed in the root. So I will completely get rid of that line in the header then.
