### ISSUE TITLE
Mobile detection

### ISSUE THREAD

**Issue by emiluzelac** [senlin/soblossom#4]
Mobile detection https://github.com/senlin/soblossom/blob/master/inc/classes/Mobile_Detect.php is unreliable and not very safe either and it will cause issues with browser caching and caching plugins. 

Headers and agents to detect users device is pretty much useless nowadays. 

See for instance core already does this ```wp_is_mobile()``` and it has been removed from Twenty Fourteen last year: https://core.trac.wordpress.org/ticket/26221

**Comment by senlin** [comment]
Sorry, I don't agree.

The `wp_is_mobile()` is too basic a function and therefore completely useless. 

The Mobile_Detect script is in very active development and I use it together with the Aqua_Resizer script to resize images  dynamically. 

I should perhaps uncomment it by default, so people can choose whether or not to activate it?

**Comment by emiluzelac** [comment]
Your call :)
