### ISSUE TITLE
Title fallback

### ISSUE THREAD

**Issue by emiluzelac** [senlin/soblossom#6]
Adding a < 4.1 fallback for ```wp_title``` such as ```if ( version_compare( $GLOBALS['wp_version'], '4.1', '<' ) ) :``` see: https://github.com/Automattic/_s/blob/master/inc/extras.php#L26-L71

**Comment by senlin** [comment]
Hmmm as soblossom is a starter theme, I would like to assume that people using it, will do so on new WP installs, not installs of 3 years ago ;)

I understand that to get through the official Theme Review I would have to change this and make it backward compatible, but as I will not submit the theme to the official Repo I will label this as "wontfix" for now.

**Comment by senlin** [comment]
replaced wontfix label with NA label
reason that it is not applicable, is because I ordered the Theme Review service not with the intend to submit soblossom to the WP.org Theme Repo, but to get an outside independent assessment of the quality of the code.
