### ISSUE TITLE
Dashicons

### ISSUE THREAD

**Issue by emiluzelac** [senlin/soblossom#7]
Can't see where this is coming from or how are you adding in? ```wp_enqueue_style( 'dashicons' );```

**Comment by senlin** [comment]
Yeah that is a strange one. In the beginning (when I was still developing soblossom) I added that in, because if I left it off, I was not able to use dashicons for example when registering Custom Post Types.

**Comment by senlin** [comment]
You're right (of course, hahaha). Just now I re-tested it and I can do without the line.
