### ISSUE TITLE
jQuery dependency 

### ISSUE THREAD

**Issue by emiluzelac** [senlin/soblossom#8]
For dependency reasons call jQuery in array instead of adding like ```wp_enqueue_script( 'jquery' );```.
Here's an example:

```wp_enqueue_script( 'soblossom-js', get_template_directory_uri() . '/js/soblossom.js', array( 'jquery' ), null, true );```

**Comment by senlin** [comment]
I don't understand, what is it exactly that you want me to do here?

**Comment by emiluzelac** [comment]
All right, so we can remove this line completely ```wp_enqueue_script( 'jquery' );``` and call the jQuery in array like it was exampled above:

```
wp_enqueue_script( 'soblossom-js', get_template_directory_uri() . '/js/soblossom.js', array( 'jquery' ), null, true );
```

This ```array( 'jquery' )``` does the same thing as this ```wp_enqueue_script( 'jquery' );```

**Comment by senlin** [comment]
Ah, okay, I didn't realise this, thanks for the tip!
