### ISSUE TITLE
Analytics/Tracking

### ISSUE THREAD

**Issue by emiluzelac** [senlin/soblossom#9]
This is being added via plugin anyways and majority of users will have this in independently.

```
	/**
	 * Sample function to add GA Universal tracking script to the site.
	 * 
	 * hooks into soblossom_body_open() function
	 * 
	 * @since 140730
	 */
	function soblossom_ga_script() { ?>
	
	<script>
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
		
		ga('create', 'UA-********-x', 'auto');
		ga('send', 'pageview');
	</script>
```

**Comment by senlin** [comment]
You are right, a lot of people unfortunately use a plugin for something as trivial as this.

By default this is not active and I basically want to use it to demonstrate that people can use this to hook something into a function. I therefore want to keep it in the theme, but I might change the wording in the description to make that more clear.

**Comment by senlin** [comment]
replaced wontfix label with NA label
reason that it is not applicable, is because I ordered the Theme Review service not with the intend to submit soblossom to the WP.org Theme Repo, but to get an outside independent assessment of the quality of the code.
